export const statusList = [
    "Discovered",
    "Approved",
    "Produced",
    "ForWholeSale",
    "ForRetail",
    "ForSale",
    "Sold"
];

export const ingredientsList = [
    "Acamprosate Calcium",
    "Acitretin",
    "Adapalene",
    "Adefovir Dipivoxil",
    "Azacitidine",
    "Bicalutamide",
    "Bivalirudin",
    "Bortezomib",
    "Calcipotriol Anhydrous",
    "Calcitonin (Salmon)",
    "Candesartan cilexetil",
    "Carvedilol",
    "Celiprolol Hydrochloride",
    "Cinacalcet HCl",
    "Ciprofloxacin",
    "Ciprofloxacin Hydrochloride",
    "Cisplatin",
    "Clarithromycin Granules 27.5%",
    "Dabigatran Etexilate Mesylate",
    "Decitabine",
    "Dronedarone",
    "Edaravone",
    "Entecavir",
    "Febuxostat Form G",
    "Fesoterodine Fumarate",
    "Finasteride",
    "Gabapentin",
    "Galantamine Hydrobromide",
    "Irbesartan",
    "Irinotecan",
    "Lenalidomide",
    "Levalbuterol HCl",
    "Lopinavir",
    "Lurasidone HCl",
    "Meropenem",
    "Mesalazine/Mesalamine",
    "Midazolam",
    "Naloxone HCl",
    "Naltrexone HCl",
    "Naratriptan HCl",
    "Olanzapine",
    "Olopatadine HCl",
    "Orlistat",
    "Oxetacaine",
    "Paliperidone",
    "Pemetrexed Disodium",
    "Pentazocine",
    "Pregabalin",
    "Rabeprazole sodium",
    "Ramipril",
    "Rifaximin",
    "Riluzole",
    "Risedronate Sodium",
    "Risperidone",
    "Ritonavir",
    "Rivastigmine Base",
    "Sertraline Hydrochloride Form I",
    "Sevelamer Carbonate",
    "Tadalafil",
    "Tamsulosin Hydrochloride",
    "Telmisartan",
    "Tolterodine tartrate",
    "Valgancyclovir Hydrochloride (Amorphous Grade)",
    "Valsartan",
    "Venlafaxine Hydrochloride",
    "Voglibose",
    "Voriconazole",
    "Zoledronic Acid",
    "Zolmitriptan",
    "Zolpidem Tartrate",
    "Zonisamide"
];
